groups:
  - name: redis-exporter-rules
    rules:
    - alert: RedisDown
      annotations:
        description: Redis instance {{  $labels.instance }} is down
        summary: Redis instance {{  $labels.instance }} of {{ $labels.service }}
          down
      expr: redis_up == 0
      for: 2m
      labels:
        namespace: utilities
        severity: error
    - alert: RedisMissingMaster
      annotations:
        description: |-
          Redis cluster has no node marked as master.
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Redis missing master (instance {{ $labels.instance }})
      expr: count(redis_instance_info{role="master"}) == 0
      for: 5m
      labels:
        severity: critical
    - alert: RedisTooManyMasters
      annotations:
        description: |-
          Redis cluster has too many nodes marked as master.
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Redis too many masters (instance {{ $labels.instance }})
      expr: count by (service) (redis_instance_info{role="master"}) > 1
      for: 5m
      labels:
        severity: critical
    - alert: RedisDisconnectedSlaves
      annotations:
        description: |-
          Redis not replicating for all slaves. Consider reviewing the redis replication status.
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Redis disconnected slaves (instance {{ $labels.instance }})
      expr: count without (instance, job) (redis_connected_slaves) - sum without
        (instance, job) (redis_connected_slaves) - 1 > 1
      for: 5m
      labels:
        severity: critical
    - alert: RedisReplicationBroken
      annotations:
        description: |-
          Redis instance lost a slave
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Redis replication broken (instance {{ $labels.instance }})
      expr: delta(redis_connected_slaves[1m]) < 0
      for: 5m
      labels:
        severity: critical
    - alert: RedisClusterFlapping
      annotations:
        description: |-
          Changes have been detected in Redis replica connection. This can occur when replica nodes lose connection to the master and reconnect (a.k.a flapping).
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Redis cluster flapping (instance {{ $labels.instance }})
      expr: changes(redis_connected_slaves[5m]) > 30
      for: 5m
      labels:
        severity: critical
    - alert: RedisTooManyConnections
      annotations:
        description: |-
          Redis instance has too many connections
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Redis too many connections (instance {{ $labels.instance }})
      expr: redis_connected_clients > 500
      for: 5m
      labels:
        severity: warning
    - alert: RedisNotEnoughConnections
      annotations:
        description: |-
          Redis instance should have more connections (> 2)
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Redis not enough connections (instance {{ $labels.instance }})
      expr: redis_connected_clients < 2
      for: 5m
      labels:
        severity: warning
    - alert: RedisRejectedConnections
      annotations:
        description: |-
          Some connections to Redis has been rejected
            VALUE = {{ $value }}
            LABELS: {{ $labels }}
        summary: Redis rejected connections (instance {{ $labels.instance }})
      expr: increase(redis_rejected_connections_total[1m]) > 0
      for: 5m
      labels:
        severity: critical
    - alert: RedisKeyEviction
      annotations:
        description: Redis instance {{ "{{ $instance }}" }} has evicted {{ $value }} keys in the last 5 minutes.
        summary: Redis instance {{ "{{ $instance }}" }} has evicted keys
      expr: increase(redis_evicted_keys_total[5m]) > 0
      for: 1s
      labels:
        namespace: utilities
        severity: error