---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: infra-node-rules
  labels:
    prometheus: infra-prometheus
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  {{ .Files.Get "rules/node.rules.yml" }}
