{{- if (eq .Values.step "snapshot") -}}
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: {{ .Release.Name }}-{{ now | date "20060102" }}
spec:
  volumeSnapshotClassName: {{ .Values.prepare.volumesnapshotclass | default "csi-ssd" | quote }}
  source:
    persistentVolumeClaimName: {{ .Release.Name }}-clone
{{- end -}}