---
apiVersion: v1
kind: Secret
metadata:
  name: infra-prometheus-scrape-configs
  labels:
    chart: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  "scrape.yaml": |-
    {{ tpl (.Files.Get "config/infra-scrapes.yaml") . | b64enc }}
