{{- range $index, $item := (lookup "v1" "Namespace" "" "").items }}
{{- $namespace := $item.metadata.name -}}
{{- if not (has $namespace $.Values.ignore) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.secretname }}
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: "{{ $.Release.Service }}"
  annotations:
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "dockerconfigjson.b64enc" $ }}
---
{{- end }}
{{- end }}