apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ $.Values.env.PVC_NAME }}-snapshot
spec:
  schedule: "{{ $.Values.cronjob.schedule }}"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-snapshot
          containers:
          - name: app
            image: "{{ $.Values.cronjob.image }}"
            imagePullPolicy: "{{ $.Values.cronjob.imagePullPolicy }}"
            env:
            {{- range $k, $v := $.Values.env }}
            - name: {{ $k | quote }}
              value: {{ $v | quote }}
            {{- end }}
            - name: "VOLUMESNAPSHOTCLASS"
              value: "csi-ssd"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            command:
            - /bin/bash
            - -c
            - /backup.sh
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: {{ $.Values.cronjob.imagePullSecretName }}
