prometheus:
  version: "v2.22.2"
  biz:
    resources:
      limits:
        cpu: 2
        memory: 10G
      requests:
        cpu: 1
        memory: 10G
    storageSize: "100G"
    thanos:
      resources:
        limits:
          cpu: 250m
          memory: 1G
        requests:
          cpu: 250m
          memory: 1G

  infra:
    resources:
      limits:
        cpu: 4
        memory: 15G
      requests:
        cpu: 2
        memory: 15G
    storageSize: "150G"
    thanos:
      resources:
        limits:
          cpu: 4
          memory: 1G
        requests:
          cpu: 2
          memory: 1G
